In [1]:
import numpy as np
list1=[1,2,3,4,5]
arr=np.array(list1)
print(arr)


[1 2 3 4 5]


In [2]:
zeros_arr=np.zeros(5)
print(zeros_arr)

[0. 0. 0. 0. 0.]


In [3]:
zeros_arr=np.zeros(5,dtype="int")
print(zeros_arr)

[0 0 0 0 0]


In [4]:
ones_arr=np.ones(5)
print(ones_arr)

[1. 1. 1. 1. 1.]


In [5]:
range_arr=np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]


In [6]:
linspace_arr=np.linspace(0,1,5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
random_array=np.random.rand(3)
print(random_array)

[0.63696195 0.08502942 0.31830442]


In [8]:
randn_arr=np.random.randn(3)
print(randn_arr)

[-0.73196487 -0.06622086  0.84773792]


In [9]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.shape(arr))

(2, 3)


In [10]:
arr=[1,2,3,4,5]
median=np.median(arr)
sum1=np.sum(arr)
std_dev=np.std(arr)
print(median)
print(sum1)
print(std_dev)
np.unique(arr)

3.0
15
1.4142135623730951


array([1, 2, 3, 4, 5])

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
transpose_arr=np.transpose(arr)
print(transpose_arr)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
import numpy as np
range_arr=np.random.randint(1000,10000)
print(range_arr)


7940


In [13]:
import numpy as np
arr=[1,2,3,4,5],[5,4,3,2,1]
mean=np.mean(arr)
median=np.median(arr)
unique_values, counts = np.unique(arr, return_counts=True)
mode = unique_values[np.argmax(counts)]
std_dev=np.std(arr)
transpose_arr=np.transpose(arr)
print(mean)
print(median)
print(mode)
print(std_dev)
print(transpose_arr)

3.0
3.0
1
1.4142135623730951
[[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]]


In [14]:
import numpy as np
arr1 = [22,6,7]
arr2 = [10,3,8]
print("Vector 1", arr1)
print("Vector 2", arr2)
print("Cross product: ",np.cross(arr1,arr2))


Vector 1 [22, 6, 7]
Vector 2 [10, 3, 8]
Cross product:  [  27 -106    6]


In [15]:
import numpy as np
arr1 = [91,41],[8,12]
arr2 = [87,34],[2,3]
print("Vector 1",arr1)
print("Vector 2",arr2)
print("Dot product: ",np.dot(arr1,arr2))

Vector 1 ([91, 41], [8, 12])
Vector 2 ([87, 34], [2, 3])
Dot product:  [[7999 3217]
 [ 720  308]]


In [17]:
import numpy as np

arr = np.array([[1, 20], [5, 4]])
print(np.shape(arr))   

print(arr.reshape(4,))     
print(arr.reshape(1, 4))   
print(arr.reshape(4, 1))   

(2, 2)
[ 1 20  5  4]
[[ 1 20  5  4]]
[[ 1]
 [20]
 [ 5]
 [ 4]]


In [19]:
import numpy as np
user_score=0
computer_score=0
for i in range(5):
    print("Round",i,":")
    userInp=int(input("Enter your choice (1 for rock, 2 for paper and 3 for scissors) : "))
    compInp=np.random.randint(1,4)
    print("Computers's choice : ",compInp)
    if(userInp==compInp):
        print("Draw")
    elif((userInp==1 and compInp==3)or(userInp==2 and compInp==1)or(userInp==3 and compInp==2)):
        print("User wins this round")
        user_score+=1
    else:
        print("Computer won this round")
        computer_score+=1
print("After 5 rounds \nScore of the user :",user_score,"\nScore of the computer :",computer_score)
if(user_score>computer_score):
    print("User wins")
else:
    print("Computer wins")



Round 0 :
Enter your choice (1 for rock, 2 for paper and 3 for scissors) : 3
Computers's choice :  3
Draw
Round 1 :
Enter your choice (1 for rock, 2 for paper and 3 for scissors) : 3
Computers's choice :  2
User wins this round
Round 2 :
Enter your choice (1 for rock, 2 for paper and 3 for scissors) : 2
Computers's choice :  3
Computer won this round
Round 3 :
Enter your choice (1 for rock, 2 for paper and 3 for scissors) : 1
Computers's choice :  3
User wins this round
Round 4 :
Enter your choice (1 for rock, 2 for paper and 3 for scissors) : 3
Computers's choice :  1
Computer won this round
After 5 rounds 
Score of the user : 2 
Score of the computer : 2
Computer wins


In [20]:
import numpy as np


arr1 = np.arange(20).reshape(1, 20)
arr2 = np.arange(20).reshape(5, 4)

reshaped_arr1 = arr1.reshape(2, 10)
reshaped_arr2 = arr2.reshape(2, 10)

print("Org Array 1:\n", arr1)
print("Org Array 2:\n", arr2)
print("Reshape Array 1:\n", reshaped_arr1)
print("Reshape Array 2:\n", reshaped_arr2)

Org Array 1:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
Org Array 2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Reshape Array 1:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Reshape Array 2:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [21]:
 def fact(n):
    if(n==1 or n==0):
        return 1
    else:
        return(n*fact(n-1))
def fact_iterative(n):
    result=1
    for i in range(1,n+1):
        result*=i
    return result
n=int(input("Enter a number: "))
print("The factorial(recursive) of",n,"is",fact(n))
print("The factorial(non-recursive) of",n,"is",fact_iterative(n))

Enter a number: 343
The factorial(recursive) of 343 is 204041444647727894832322663397251900658245332324390400529489242223120675094188773114043975799743992919578121862904221538707624613539651617735241304823433436143266461705767566584680005983534555108566627714057772167106506278461879916565954729928846028000454704474107577615388226190068321524291467011878325877132356129908197680574487841393438405895672964096092783542137458755938126723479967598884044727550474402522264572563730271549684118667663915926753884781245932247800208523136927533775595342210049945491110284451604187735397616527464845239386084578367781811330601019717014971878449223769083849020700195533187250240612211539806462750071193600000000000000000000000000000000000000000000000000000000000000000000000000000000000
The factorial(non-recursive) of 343 is 20404144464772789483232266339725190065824533232439040052948924222312067509418877311404397579974399291957812186290422153870762461353965161773524130482343343614326646170576756658468000

In [24]:
num_to_string = {1:'january', 2:'february', 3:'march', 4:'april', 5:'may', 6:'june', 7:'july', 8:'august', 9:'september', 10:'october', 11:'november', 12:'december'}
string_to_num={'january':1, 'february':2, 'march':3, 'april':4, 'may':5, 'june':6, 'july':7, 'august':8, 'september':9, 'october':10, 'november':11, 'december':12}
birth_month=str(input(print("Enter your birth month (as string) : ")))
if(type(birth_month)==str):
    print("Birth Month in number is :",string_to_num[birth_month])
else:
    if(birth_month<12):
        print("Birth Month (as a string) :",num_to_string[bith_month])
    else:
        print("Enter a valid birth month")

Enter your birth month (as string) : 
Nonemarch
Birth Month in number is : 3


In [28]:
number_to_str = {1: "January",2: "February",3: "March",4: "April",5: "May",6: "June",7: "July",8: "August",9: "September",10: "October",11: "November",12: "December"}

str_to_number = {"January": 1,"February": 2,"March": 3,"April": 4,"May": 5,"June": 6,"July": 7,"August": 8,"September": 9,"October": 10,"November": 11,"December": 12}

birth_month_num = int(input("Enter your birth month in number: "))


birth_month_name = number_to_str[birth_month_num]
print("Your birth month is:", birth_month_name)


birth_month_str = input("Enter your birth month in string: ")

birth_month_number = str_to_number[birth_month_str]
print("Your birth month number is:", birth_month_number)

Enter your birth month in number: 4
Your birth month is: April
Enter your birth month in string: April
Your birth month number is: 4
